language: node_js
node_js:
  - 11.2.0
cache: npm
before_install:
  - cd establish
install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install
script: npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "establish-pwa"
  skip_cleanup: true
  local_dir: build
  acl: public_read
  on:
    all_branches: true
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
