version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd establish
      - npm install
      - npm run build
      - aws s3 sync build s3://welcomeidaho.com --delete
